Ruby/lvrug/rails/todo/config/routes.rb
Todo::Application.routes.draw do
  resources :tasks

  root :to => 'tasks#index'

end

Ruby/lvrug/rails/todo/app/models/task.rb
class Task < ActiveRecord::Base
  attr_accessible :item, :description
end

Ruby/lvrug/rails/todo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Ruby/lvrug/rails/todo/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(params[:task])
    if @task.save
      redirect_to @task, :notice => "Successfully created task."
    else
      render :action => 'new'
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update_attributes(params[:task])
      redirect_to @task, :notice  => "Successfully updated task."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_url, :notice => "Successfully destroyed task."
  end
end

Ruby/lvrug/rails/todo/app/helpers/application_helper.rb
module ApplicationHelper
end

Ruby/lvrug/rails/todo/app/helpers/error_messages_helper.rb
module ErrorMessagesHelper
  # Render error messages for the given objects. The :message and :header_message options are allowed.
  def error_messages_for(*objects)
    options = objects.extract_options!
    options[:header_message] ||= I18n.t(:"activerecord.errors.header", :default => "Invalid Fields")
    options[:message] ||= I18n.t(:"activerecord.errors.message", :default => "Correct the following errors and try again.")
    messages = objects.compact.map { |o| o.errors.full_messages }.flatten
    unless messages.empty?
      content_tag(:div, :class => "error_messages") do
        list_items = messages.map { |msg| content_tag(:li, msg) }
        content_tag(:h2, options[:header_message]) + content_tag(:p, options[:message]) + content_tag(:ul, list_items.join.html_safe)
      end
    end
  end

  module FormBuilderAdditions
    def error_messages(options = {})
      @template.error_messages_for(@object, options)
    end
  end
end

ActionView::Helpers::FormBuilder.send(:include, ErrorMessagesHelper::FormBuilderAdditions)

Ruby/lvrug/rails/todo/app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { h(page_title.to_s) }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

Ruby/lvrug/rails/todo/app/helpers/tasks_helper.rb
module TasksHelper
end

Ruby/lvrug/rails/todo/app/views/layouts/application.html.haml
!!!
%html

  %head
    %title
      = yield(:title) || "Untitled"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = stylesheet_link_tag "application"
    = javascript_include_tag :application
    = csrf_meta_tag
    = yield(:head)

  %body
    #container
      - flash.each do |name, msg|
        = content_tag :div, msg, :id => "flash_#{name}"

      - if show_title?
        %h1= yield(:title)

      = yield

Ruby/lvrug/rails/todo/app/views/tasks/_form.html.haml
= form_for @task do |f|
  = f.error_messages
  %p
    = f.label :item
    %br
    = f.text_field :item
  %p
    = f.label :description
    %br
    = f.text_field :description
  %p
    = f.submit

Ruby/lvrug/rails/todo/app/views/tasks/edit.html.haml
- title "Edit Task"

= render 'form'

%p
  = link_to "Show", @task
  |
  = link_to "View All", tasks_path

Ruby/lvrug/rails/todo/app/views/tasks/index.html.haml
- title "Tasks"

%table
  %tr
    %th Item
    %th Description
  - for task in @tasks
    %tr
      %td= task.item
      %td= task.description
      %td= link_to 'Show', task
      %td= link_to 'Edit', edit_task_path(task)
      %td= link_to 'Destroy', task, :confirm => 'Are you sure?', :method => :delete

%p= link_to "New Task", new_task_path

Ruby/lvrug/rails/todo/app/views/tasks/new.html.haml
- title "New Task"

= render 'form'

%p= link_to "Back to List", tasks_path

Ruby/lvrug/rails/todo/app/views/tasks/show.html.haml
- title "Task"

%p
  %strong Item:
  = @task.item
%p
  %strong Description:
  = @task.description

%p
  = link_to "Edit", edit_task_path(@task)
  |
  = link_to "Destroy", @task, :confirm => 'Are you sure?', :method => :delete
  |
  = link_to "View All", tasks_path